### ISSUE TITLE
Error generating English text. How to fix?

### ISSUE THREAD

**Issue by GenTxt** [GaoPeng97/transformer-xl-chinese#8]
Hi:

Thanks for the repo. Using google translate I now have the following steps working 100%. I modified one of your bash scripts as per your instructions and use data_utils.py and renamed old_vocabulary.py for English.

I am using values same as "doupo" and --dataset=text8

Input is a 8 meg utf-8 text files (train.txt, valid.txt, test.txt)

text8.sh train_data (works - files created)

text8.sh test_data (works)

text8.sh train (works - models generated)

text8.sh eval (works - report to terminal)

Edit script for inference:

Delete: --do_eval=True \

Add:     --do_inference=True \

Run text8.sh eval again ... starts then following error:
etc.
  File "train_gpu.py", line 499, in main
    inference(n_token, cutoffs, "/gpu:0")
  File "train_gpu.py", line 506, in inference
    tmp_Vocab.count_file("../data/{}/train.txt".format(dataset_name), add_eos=False)
  File "/home/pixelhead/Desktop/Transformer-XL-PROBLEMS/transformer-xl-textgen/tf/vocabulary.py", line 48, in count_file

Any suggestions on how I can fix this?  
Thanks,

**Comment by GaoPeng97** [comment]
Hi， this is the problem caused by vocabulary.py .  There are some differences in spliting Chinese sentence in to words and spliting English sentence into words. In English, it is splited by space. However, there is no space in Chinese.  So I suggest that you can use old_vocabulary.py to repalce vocabulary.py in the code and try again. The old_vocabulary is reserved from original transformer xl, and that is for English. Good luck.

**Comment by GenTxt** [comment]
Thanks for the reply. I've been using old_vocabulary.py renamed as
vocabulary.py and the error persists.

Running repo under ubuntu 18.04 and tensorflow 1.14

**Comment by GaoPeng97** [comment]
From your log info, though I can not figure out where is exactly the error, It seems that it is not difficult to solve. I suggest you dive in to the count_file function in vocabulay.py,  and to make sure that sentences in the file have been splited in this function.
